FROM node:20-bullseye

# Installation de Cloudflared
RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
RUN dpkg -i cloudflared-linux-amd64.deb || true
RUN apt-get install -f -y

WORKDIR /app
RUN npm install express
COPY portal.js ./

EXPOSE 8080
CMD ["node", "portal.js"]
